### ISSUE TITLE
pm_fao56 error

### ISSUE THREAD

**Issue by WARD-CODE** [pyet-org/pyet#53]
i got some errors using the pm_fao56 method 
Traceback (most recent call last):
  File "FAO/Evapotranspiration.py", line 239, in <module>
    s = pm_fao56(tmean=16,wind=5,rn = 2.3,tmax=16,tmin=16,rh=81,elevation=2,pressure=101.6,clip_zero=False)
  File "C:\Users\wardi\AppData\Local\Programs\Python\Python37\lib\site-packages\pyet\combination.py", line 484, in pm_fao56
    return pet.rename("PM_FAO_56")
AttributeError: 'numpy.float64' object has no attribute 'rename'

Traceback (most recent call last):
  File "FAO/Evapotranspiration.py", line 239, in <module>
    s = pm_fao56(tmean=16,wind=5,rn = 2.3,tmax=16,tmin=16,rh=81,elevation=2,pressure=101.6,clip_zero=True)
  File "C:\Users\wardi\AppData\Local\Programs\Python\Python37\lib\site-packages\pyet\combination.py", line 483, in pm_fao56
    pet = clip_zeros(pet, clip_zero)
  File "C:\Users\wardi\AppData\Local\Programs\Python\Python37\lib\site-packages\pyet\utils.py", line 81, in clip_zeros
    return s.where((s > 0) | (s.isnull()), 0)
AttributeError: 'numpy.float64' object has no attribute 'where'

**Comment by mvremec** [comment]
Hi Wardi,

the input for the meteorological variables must be either `Pandas.Series` or `xarray.DataArray`. I would recommend you to check the provided [examples](https://github.com/pyet-org/pyet/tree/master/examples).

The easiest way is to create a pandas.DataFrame:
```
import pyet
meteo = pd.DataFrame({"tmean":16, "wind":5, "rn":2.3, "rh":81, "elevation":2}, 
                       index=[pd.Timestamp("2023-4-18")])
s = pyet.pm_fao56(tmean=meteo["tmean"], wind=meteo["wind"], rn=meteo["rn"], rh=meteo["rh"], 
                  elevation=meteo["elevation"])
```

Best,
Matevz

**Comment by medilies** [comment]
Thank you for giving a fast response @mvremec
